/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/7.2/userguide/multi_project_builds.html
 */

 // this is a bit of a hack to allow setting the ruleset here
 // and telling the settings to include it in projects to build
 // but also allow the build scripts to know which ruleset was built
fun defineVar(name: String, value: String): String {
    val g = (gradle as ExtensionAware)
    g.extra[name] = value
    return value
}

dependencyResolutionManagement {
    versionCatalogs {
        create("libs") {
            version("kotlin", "1.7.21")
            plugin("kotlinter", "org.jmailen.kotlinter").version("3.13.0")
            plugin("testlogger", "com.adarshr.test-logger").version("3.2.0")
            library("mockk", "io.mockk", "mockk").version("1.13.3")
            library("kotlinx-serialization", "org.jetbrains.kotlinx", "kotlinx-serialization-json").version("1.4.1")
        }
    }
}


rootProject.name = "lemuria"
val engineVersion = defineVar("engineVersion", "0.0.1 ")

include(
    "engine",
    "core",
)